import sqlite3


class BaseYachtDatabase:
    def __init__(self, db_path="data/base_yachts.db"):
        self.conn = sqlite3.connect(db_path)
        self.create_table()

    def create_table(self):
        self.conn.execute('''
        CREATE TABLE IF NOT EXISTS base_yachts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            yacht_class TEXT,
            model TEXT,
            version TEXT,
            builder TEXT,
            designer TEXT,
            year_introduced INTEGER,
            production_start INTEGER,
            production_end INTEGER,
            country_of_origin TEXT,
            notes TEXT,
            hull_type TEXT,
            loa INTEGER,
            lwl INTEGER,
            beam INTEGER,
            draft INTEGER,
            displacement INTEGER,
            ballast INTEGER,
            construction TEXT,
            keel_type TEXT,
            keel_draft REAL,
            rudder_type TEXT,
            rig_type TEXT,
            boom_above_deck REAL,
            mh_frac TEXT,
            i REAL,
            j REAL,
            p REAL,
            e REAL,
            mizzen_i REAL,
            mizzen_j REAL,
            mizzen_p REAL,
            mizzen_e REAL,
            genoa_i REAL,
            genoa_j REAL,
            main_p REAL,
            main_e REAL,
            codezero_i REAL,
            codezero_j REAL,
            jib_i REAL,
            jib_j REAL,
            spin_i REAL,
            spin_j REAL,
            staysail_i REAL,
            staysail_j REAL,
            trisail_i REAL,
            trisail_j REAL,
            mainsail TEXT,
            jib TEXT,
            genoa TEXT,
            symmetric_spinnaker TEXT,
            asymmetric_spinnaker TEXT,
            codezero TEXT,
            staysail TEXT,
            trisail TEXT,
            stormjib TEXT, 
            mast_height REAL,
            mizzen_mast_height REAL,
            bury REAL,
            bury_mizzen REAL,
            DK_or_KL REAL,
            DK_or_KL_mizzen REAL,
            No_of_spreaders INTEGER,
            spreader_angle REAL,
            No_of_spreaders_mizzen INTEGER,
            spreader_angle_mizzen REAL,
            mast_section TEXT,
            mast_section_mizzen TEXT,
            boom_section TEXT,
            boom_section_mizzen TEXT,
            spin_pole_diameter REAL,
            telescope_pole_diameter REAL,
            rodkicker TEXT,
            headsail_furler TEXT,
            max_hoist REAL,
            jocky_pole TEXT,          
                              
            forestay_wire_size INTEGER,
            forestay_wire_upper INTEGER,
            forestay_wire_lower INTEGER,
            forestay_wire_length INTEGER,
                          
            mizzen_forestay_wire_size INTEGER,
            mizzen_forestay_wire_upper TEXT,
            mizzen_forestay_wire_lower TEXT,
            mizzen_forestay_wire_length INTEGER,
                          
            backstay_type TEXT,
            backstay_wire_size INTEGER,
            backstay_wire_upper TEXT,
            backstay_wire_lower TEXT,
            backstay_wire_length INTEGER,
                          
            mizzen_backstay_type INTEGER,
            mizzen_backstay_wire_size INTEGER,
            mizzen_backstay_wire_upper TEXT,
            mizzen_backstay_wire_lower TEXT,
            mizzen_backstay_wire_length INTEGER,
                                   
            capshrouds_wire_size INTEGER,
            capshrouds_wire_upper TEXT,
            capshrouds_wire_lower TEXT,
            capshrouds_wire_length INTEGER,
                          
            mizzen_capshrouds_wire_size INTEGER,
            mizzen_capshrouds_wire_upper TEXT,
            mizzen_capshrouds_wire_lower TEXT,
            mizzen_capshrouds_wire_length INTEGER,
                          
            intermediate_shrouds_wire_size INTEGER,
            intermediate_shrouds_wire_upper TEXT,
            intermediate_shrouds_wire_lower TEXT,
            intermediate_shrouds_wire_length INTEGER,
                          
            mizzen_intermediate_shrouds_wire_size INTEGER,
            mizzen_intermediate_shrouds_wire_upper TEXT,
            mizzen_intermediate_shrouds_wire_lower TEXT,
            mizzen_intermediate_shrouds_length INTEGER,
                          
            forward_lower_shrouds_wire_size INTEGER,
            forward_lower_shrouds_wire_size INTEGER,
            forward_lower_shrouds_wire_upper TEXT,
            forward_lower_shrouds_wire_lower TEXT,
            forward_lower_shrouds_wire_length INTEGER,
                          
            mizzen_forward_lower_shrouds_wire_size INTEGER,
            mizzen_forward_lower_shrouds_wire_upper TEXT,
            mizzen_forward_lower_shrouds_wire_lower TEXT,
            mizzen_forward_lower_shrouds_wire_length INTEGER,
                          
            aft_lower_shrouds_wire_size INTEGER,
            aft_lower_shrouds_wire_upper TEXT,
            aft_lower_shrouds_wire_lower TEXT,
            aft_lower_shrouds_wire_length INTEGER,
                          
            mizzen_aft_lower_shrouds_wire_size INTEGER,
            mizzen_aft_lower_shrouds_wire_upper TEXT,
            mizzen_aft_lower_shrouds_wire_lower TEXT,
            mizzen_aft_lower_shrouds_wire_length INTEGER,
                          
            inner_forestay_wire_size INTEGER,
            inner_forestay_wire_upper TEXT,
            inner_forestay_wire_lower TEXT,
            inner_forestay_wire_length INTEGER,
                          
            runner_wire_size INTEGER,
            runner_wire_upper TEXT,
            runner_wire_lower TEXT,
            runner_wire_length INTEGER,
            mizzen_runner_wire_size INTEGER,
            mizzen_runner_wire_upper TEXT,
            mizzen_runner_wire_lower TEXT,
            mizzen_runner_wire_length INTEGER,
            babystay_wire_size INTEGER,
            babystay_wire_upper TEXT,
            babystay_wire_lower TEXT,
            babystay_wire_length INTEGER,
            triatic_stay_wire_size INTEGER,
            triatic_stay_wire_upper TEXT,
            triatic_stay_wire_lower TEXT,
            triatic_stay_wire_length INTEGER,
            jumper_wire_size INTEGER,
            jumper_wire_upper TEXT,
            jumper_wire_lower TEXT,
            jumper_wire_length INTEGER,
            mizzen_jumper_wire_size INTEGER,
            mizzen_jumper_wire_upper TEXT,
            mizzen_jumper_wire_lower TEXT,
            mizzen_jumper_wire_length INTEGER,
            v1_wire_size INTEGER,
            v1_wire_upper TEXT,
            v1_wire_lower TEXT,
            v1_wire_length INTEGER,
            v2_wire_size INTEGER,
            v2_wire_upper TEXT,
            v2_wire_lower TEXT,
            v2_wire_length INTEGER,
            v2_d3_wire_size INTEGER,
            v2_d3_wire_upper TEXT,
            v2_d3_wire_lower TEXT,
            v2_d3_wire_length INTEGER,
            d1a_wire_size INTEGER,
            d1a_wire_upper TEXT,
            d1a_wire_lower TEXT,
            d1a_wire_length INTEGER,
            d1f_wire_size INTEGER,
            d1f_wire_upper TEXT,
            d1f_wire_lower TEXT,
            d1f_wire_length INTEGER,
            d2_wire_size INTEGER,
            d2_wire_upper TEXT,
            d2_wire_lower TEXT,
            d2_wire_length INTEGER,
            d3_wire_size INTEGER,
            d3_wire_upper TEXT,
            d3_wire_lower TEXT,
            d3_wire_length INTEGER
        )
        ''')
        self.conn.commit()

    def close(self):
        self.conn.close()
