import type { Boat } from "./types"

export const boatData: Boat[] = [
  {
    id: "1",
    name: "Sea Breeze",
    manufacturer: "Catalina",
    model: "34",
    year: 2018,
    type: "Cruiser",
    designer: "Gerry Douglas",
    description:
      "A well-maintained cruising sailboat perfect for coastal sailing and weekend getaways. Features a spacious cockpit and comfortable interior.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    hull: {
      length: 34.0,
      waterlineLength: 29.5,
      beam: 11.3,
      draft: 5.5,
      displacement: 5400,
      ballast: 2200,
      material: "Fiberglass",
      keelType: "Fin Keel",
      hullType: "Monohull",
      rudderType: "Spade Rudder",
      ballastRatio: 40.7,
      displacementLengthRatio: 280,
      sailAreaDisplacementRatio: 16.8,
      capsizeScreeningValue: 2.1,
    },
    rig: {
      type: "Sloop",
      mastType: "Deck Stepped",
      mastHeight: 48.5,
      mastMaterial: "Aluminum",
      boomLength: 12.8,
      boomMaterial: "Aluminum",
      standingRigging: {
        forestay: { material: "1x19 Stainless Steel", diameter: 8 },
        backstay: { material: "1x19 Stainless Steel", diameter: 8 },
        shrouds: { material: "1x19 Stainless Steel", diameter: 6 },
      },
      runningRigging: {
        halyards: { count: 3, material: "Polyester/Dyneema" },
        sheets: { count: 4, material: "Polyester Double Braid" },
      },
    },
    sailData: {
      I: 42.0,
      J: 13.5,
      P: 38.0,
      E: 12.8,
      mainsailArea: 243,
      foretriangle: 284,
      totalSailArea100: 527,
      totalSailArea150: 669,
      spinnakerArea: 850,
      downwindSailArea: 1093,
      sailAreaDisplacementRatio: 16.8,
      displacementLengthRatio: 280,
      ballastDisplacementRatio: 40.7,
      capsizeScreeningValue: 2.1,
    },
    sails: [
      {
        type: "Mainsail",
        material: "Dacron",
        area: 243,
        condition: 8,
        year: 2018,
        manufacturer: "Catalina Sails",
        notes: "Full-battened mainsail with 2 reef points",
        windRange: "5-25",
      },
      {
        type: "Genoa",
        material: "Dacron",
        area: 426,
        condition: 7,
        year: 2018,
        manufacturer: "Catalina Sails",
        notes: "135% genoa with UV protection strip",
        windRange: "5-20",
      },
      {
        type: "Jib",
        material: "Dacron",
        area: 284,
        condition: 9,
        year: 2020,
        manufacturer: "North Sails",
        notes: "100% working jib, excellent condition",
        windRange: "15-30",
      },
      {
        type: "Spinnaker",
        material: "Nylon",
        area: 850,
        condition: 6,
        year: 2016,
        manufacturer: "Doyle Sails",
        notes: "Asymmetric spinnaker, some minor repairs needed",
        windRange: "5-18",
      },
    ],
    ropes: [
      {
        name: "Main Halyard",
        category: "Running Rigging",
        material: "Polyester/Dyneema",
        diameter: 10,
        length: 55,
        condition: 8,
      },
      {
        name: "Jib Halyard",
        category: "Running Rigging",
        material: "Polyester/Dyneema",
        diameter: 8,
        length: 50,
        condition: 7,
      },
      {
        name: "Spinnaker Halyard",
        category: "Running Rigging",
        material: "Polyester",
        diameter: 8,
        length: 52,
        condition: 6,
      },
      {
        name: "Main Sheet",
        category: "Running Rigging",
        material: "Polyester Double Braid",
        diameter: 12,
        length: 25,
        condition: 9,
      },
      {
        name: "Jib Sheets",
        category: "Running Rigging",
        material: "Polyester Double Braid",
        diameter: 10,
        length: 20,
        condition: 8,
      },
      {
        name: "Outhaul",
        category: "Control Lines",
        material: "Polyester",
        diameter: 6,
        length: 8,
        condition: 7,
      },
      {
        name: "Cunningham",
        category: "Control Lines",
        material: "Polyester",
        diameter: 6,
        length: 6,
        condition: 8,
      },
      {
        name: "Boom Vang",
        category: "Control Lines",
        material: "Polyester",
        diameter: 8,
        length: 10,
        condition: 9,
      },
      {
        name: "Bow Line",
        category: "Docking Lines",
        material: "Nylon Three Strand",
        diameter: 16,
        length: 15,
        condition: 8,
      },
      {
        name: "Stern Line",
        category: "Docking Lines",
        material: "Nylon Three Strand",
        diameter: 16,
        length: 15,
        condition: 8,
      },
      {
        name: "Spring Lines",
        category: "Docking Lines",
        material: "Nylon Three Strand",
        diameter: 14,
        length: 20,
        condition: 7,
      },
    ],
  },
  {
    id: "2",
    name: "Wind Dancer",
    manufacturer: "Beneteau",
    model: "Oceanis 40.1",
    year: 2020,
    type: "Cruiser",
    designer: "Finot-Conq Architects",
    description:
      "Modern cruising yacht with excellent performance and comfort. Features a spacious interior and advanced sail handling systems.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    hull: {
      length: 39.9,
      waterlineLength: 35.4,
      beam: 12.9,
      draft: 6.9,
      displacement: 7800,
      ballast: 2900,
      material: "Fiberglass",
      keelType: "L-Shaped Keel",
      hullType: "Monohull",
      rudderType: "Twin Rudders",
      ballastRatio: 37.2,
      displacementLengthRatio: 245,
      sailAreaDisplacementRatio: 18.2,
      capsizeScreeningValue: 1.9,
    },
    rig: {
      type: "Sloop",
      mastType: "Deck Stepped",
      mastMaterial: "Aluminum",
      mastHeight: 56.7,
      boomLength: 14.2,
      boomMaterial: "Aluminum",
      standingRigging: {
        forestay: { material: "1x19 Stainless Steel", diameter: 10 },
        backstay: { material: "1x19 Stainless Steel", diameter: 10 },
        shrouds: { material: "1x19 Stainless Steel", diameter: 8 },
      },
      runningRigging: {
        halyards: { count: 4, material: "Dyneema Core" },
        sheets: { count: 6, material: "Polyester/Dyneema" },
      },
    },
    sailData: {
      I: 50.2,
      J: 15.7,
      P: 44.6,
      E: 14.2,
      mainsailArea: 317,
      foretriangle: 394,
      totalSailArea100: 711,
      totalSailArea150: 908,
      spinnakerArea: 1150,
      downwindSailArea: 1467,
      sailAreaDisplacementRatio: 18.2,
      displacementLengthRatio: 245,
      ballastDisplacementRatio: 37.2,
      capsizeScreeningValue: 1.9,
    },
    sails: [
      {
        type: "Mainsail",
        material: "Dacron",
        area: 317,
        condition: 9,
        year: 2020,
        manufacturer: "Beneteau Sails",
        notes: "Full-battened mainsail with lazy jacks",
        windRange: "5-30",
      },
      {
        type: "Genoa",
        material: "Dacron",
        area: 591,
        condition: 9,
        year: 2020,
        manufacturer: "Beneteau Sails",
        notes: "150% furling genoa with UV protection",
        windRange: "5-22",
      },
      {
        type: "Code Zero",
        material: "Laminate",
        area: 750,
        condition: 8,
        year: 2021,
        manufacturer: "North Sails",
        notes: "Light air reaching sail",
        windRange: "3-15",
      },
    ],
    ropes: [
      {
        name: "Main Halyard",
        category: "Running Rigging",
        material: "Dyneema Core",
        diameter: 12,
        length: 65,
        condition: 9,
      },
      {
        name: "Genoa Halyard",
        category: "Running Rigging",
        material: "Dyneema Core",
        diameter: 10,
        length: 60,
        condition: 9,
      },
      {
        name: "Main Sheet",
        category: "Running Rigging",
        material: "Polyester/Dyneema",
        diameter: 14,
        length: 30,
        condition: 9,
      },
      {
        name: "Genoa Sheets",
        category: "Running Rigging",
        material: "Polyester/Dyneema",
        diameter: 12,
        length: 25,
        condition: 9,
      },
    ],
  },
  {
    id: "3",
    name: "Racing Edge",
    manufacturer: "J/Boats",
    model: "J/105",
    year: 2015,
    type: "Racer",
    designer: "Rod Johnstone",
    description:
      "High-performance one-design racing yacht. Optimized for competitive sailing with excellent upwind performance.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    hull: {
      length: 34.5,
      waterlineLength: 28.5,
      beam: 11.2,
      draft: 6.5,
      displacement: 4200,
      ballast: 1900,
      material: "Fiberglass",
      keelType: "Fin Keel",
      hullType: "Monohull",
      rudderType: "Spade Rudder",
      ballastRatio: 45.2,
      displacementLengthRatio: 195,
      sailAreaDisplacementRatio: 21.5,
      capsizeScreeningValue: 1.8,
    },
    rig: {
      type: "Sloop",
      mastType: "Keel Stepped",
      mastMaterial: "Carbon Fiber",
      mastHeight: 52.0,
      boomLength: 13.5,
      boomMaterial: "Carbon Fiber",
      standingRigging: {
        forestay: { material: "Rod Rigging", diameter: 12 },
        backstay: { material: "Rod Rigging", diameter: 12 },
        shrouds: { material: "Rod Rigging", diameter: 10 },
      },
      runningRigging: {
        halyards: { count: 5, material: "Dyneema" },
        sheets: { count: 8, material: "Spectra/Polyester" },
      },
    },
    sailData: {
      I: 45.0,
      J: 14.8,
      P: 42.0,
      E: 13.5,
      mainsailArea: 284,
      foretriangle: 333,
      totalSailArea100: 617,
      totalSailArea150: 784,
      spinnakerArea: 1050,
      downwindSailArea: 1334,
      sailAreaDisplacementRatio: 21.5,
      displacementLengthRatio: 195,
      ballastDisplacementRatio: 45.2,
      capsizeScreeningValue: 1.8,
    },
    sails: [
      {
        type: "Mainsail",
        material: "Laminate",
        area: 284,
        condition: 7,
        year: 2019,
        manufacturer: "North Sails",
        notes: "Racing mainsail with full battens",
        windRange: "5-35",
      },
      {
        type: "Jib",
        material: "Laminate",
        area: 333,
        condition: 8,
        year: 2020,
        manufacturer: "Quantum Sails",
        notes: "100% racing jib",
        windRange: "8-35",
      },
      {
        type: "Genoa",
        material: "Laminate",
        area: 451,
        condition: 6,
        year: 2017,
        manufacturer: "North Sails",
        notes: "135% racing genoa, needs minor repair",
        windRange: "5-20",
      },
      {
        type: "Spinnaker",
        material: "Nylon",
        area: 1050,
        condition: 9,
        year: 2021,
        manufacturer: "Doyle Sails",
        notes: "Symmetric spinnaker for racing",
        windRange: "5-20",
      },
    ],
    ropes: [
      {
        name: "Main Halyard",
        category: "Running Rigging",
        material: "Dyneema",
        diameter: 8,
        length: 58,
        condition: 8,
      },
      {
        name: "Jib Halyard",
        category: "Running Rigging",
        material: "Dyneema",
        diameter: 8,
        length: 55,
        condition: 9,
      },
      {
        name: "Spinnaker Halyard",
        category: "Running Rigging",
        material: "Dyneema",
        diameter: 8,
        length: 60,
        condition: 8,
      },
    ],
  },
]
